spring:
  config:
    activate:
      on-profile: test
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: always

  redis:
    host: localhost
    port: 6379
  upload:
    path: /home/ec2-user/www

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:safeking
    #    url: jdbc:h2:tcp://localhost/~/safeking
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
  #        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
