spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/safeking_dev
    username: safeking_dev
    password: 1234

  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    open-in-view: false
  logging.level:
    org.hibernate.SQL: debug
  redis:
    host: localhost
    port: 6379
  upload:
    path: /home/ec2-user/www