= Member-SIGN UP-API
backtony.github.io
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[Member-API]]
== Member API

[[Member-signup-1]]
=== Member SIGN UP_1(1. 회원가입 필수 정보)
operation::signUpCriticalItems[snippets='http-request,request-fields,request-body,http-response,response-body']

[[Member-signup-2]]
=== Member SIGN UP_2(2. 회원가입 인증 정보)
operation::signUpAuthenticationInfo[snippets='http-request,path-parameters,request-fields,request-body,http-response,response-body']

[[Member-signup-3]]
=== Member SIGN UP_3(3. 회원가입 회원 정보)
operation::signUpMemberInfo[snippets='http-request,path-parameters,request-fields,request-body,http-response,response-body']

[[Member-signup-4]]
=== Member SIGN UP_4(4. 회원가입 회원 정보)
operation::signUpAgreementInfo[snippets='http-request,path-parameters,request-fields,request-body,http-response,response-body']

[[Member-signup-DELETE]]
=== Member SIGN UP DELETE(메모리에서 회원 지우기)
operation::memoryMemberRepoClear[snippets='http-request,path-parameters,request-body,http-response']

