= SMS-API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[SMS-API]]
== SMS API

[[SMS-1]]
=== 1. 코드 전송
operation::sendCodeToClient[snippets='http-request,request-fields,http-response,response-body']

[[SMS-2]]
=== 2. 코드 확인
|===
| 설명 | 코드 일치시 status 200
|===
operation::checkCode[snippets='http-request,request-fields,http-response,response-body']

[[SMS-3]]
=== 3. 코드 확인 error
|===
| 설명 | 코드 일치시 status 400, error 응답
|===
operation::checkCode_error[snippets='http-request,request-fields,http-response,response-fields,response-body']

[[SMS-4]]
=== 4. 아이디 찾기 시에 코드 전송

operation::sendCodeToClientByIdFind[snippets='http-request,request-fields,http-response,response-body']

[[SMS-5]]
=== 4-1. 아이디 찾기 시에 코드 전송시 실패V1
|===
| 설명 | 이름이 일치하지 않을 시
|===
operation::sendCodeToClientByIdFindErrorV1[snippets='http-request,request-fields,http-response,response-body']

[[SMS-6]]
=== 4-2. 아이디 찾기 시에 코드 전송 실패V2
|===
| 설명 | 전화번호가 일치 하지 않을 시
|===
operation::sendCodeToClientByIdFindErrorV2[snippets='http-request,request-fields,http-response,response-body']
